server:
  port: 10102
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    com:
      gs:
        owner:
          generator:
            repository: debug
#    root: debug

#spring:
#  thymeleaf:
#    prefix: classpath:/page/

